\i events/BASIC_COMMAND_EVENT.sql
\i events/CHAT_EVENT.sql
\i events/PLAYER_LEAVE_EVENT.sql
\i events/PLAYER_SETUP_EVENT.sql
\i events/PLAYER_STATS_EVENT.sql
\i events/UNIT_BORN_EVENT.sql
\i events/UNIT_DIED_EVENT.sql
\i events/UNIT_DONE_EVENT.sql
\i events/UNIT_INIT_EVENT.sql
\i events/UPGRADE_COMPLETE_EVENT.sql
