from sqlalchemy import Column, Integer, Text, Float, ForeignKey
from sqlalchemy.orm import relationship

from database.base import Base

class player_stats_event(Base):
    __tablename__ = "player_stats_event"
    __table_args__ = {"schema": "events"}

    primary_id = Column(Integer, primary_key=True)

    name = Column(Text)
    second = Column(Float)
    minerals_current = Column(Float)
    vespene_current = Column(Float)
    minerals_collection_rate = Column(Float)
    vespene_collection_rate = Column(Float)
    workers_active_count = Column(Float)
    minerals_used_in_progress_army = Column(Float)
    minerals_used_in_progress_economy = Column(Float)
    minerals_used_in_progress_technology = Column(Float)
    minerals_used_in_progress = Column(Float)
    vespene_used_in_progress_army = Column(Float)
    vespene_used_in_progress_economy = Column(Float)
    vespene_used_in_progress_technology = Column(Float)
    vespene_used_in_progress = Column(Float)
    resources_used_in_progress = Column(Float)
    minerals_used_current_army = Column(Float)
    minerals_used_current_economy = Column(Float)
    minerals_used_current_technology = Column(Float)
    minerals_used_current = Column(Float)
    vespene_used_current_army = Column(Float)
    vespene_used_current_economy = Column(Float)
    vespene_used_current_technology = Column(Float)
    vespene_used_current = Column(Float)
    resources_used_current = Column(Float)
    minerals_lost_army = Column(Float)
    minerals_lost_economy = Column(Float)
    minerals_lost_technology = Column(Float)
    minerals_lost = Column(Float)
    vespene_lost_army = Column(Float)
    vespene_lost_economy = Column(Float)
    vespene_lost_technology = Column(Float)
    vespene_lost = Column(Float)
    resources_lost = Column(Float)
    minerals_killed_army = Column(Float)
    minerals_killed_economy = Column(Float)
    minerals_killed_technology = Column(Float)
    minerals_killed = Column(Float)
    vespene_killed_army = Column(Float)
    vespene_killed_economy = Column(Float)
    vespene_killed_technology = Column(Float)
    vespene_killed = Column(Float)
    resources_killed = Column(Float)
    food_used = Column(Float)
    food_made = Column(Float)
    minerals_used_active_forces = Column(Float)
    vespene_used_active_forces = Column(Float)
    ff_minerals_lost_army = Column(Float)
    ff_minerals_lost_economy = Column(Float)
    ff_minerals_lost_technology = Column(Float)
    ff_vespene_lost_army = Column(Float)
    ff_vespene_lost_economy = Column(Float)
    ff_vespene_lost_technology = Column(Float)

    player_id = Column(Integer, ForeignKey("replay.player.primary_id"))
    player = relationship("player", back_populates="player_stats_events")

    info_id = Column(Integer, ForeignKey("replay.info.primary_id"))
    info = relationship("info", back_populates="player_stats_events")
