\i events/basic_command_event.sql
\i events/chat_event.sql
\i events/player_leave_event.sql
\i events/player_setup_event.sql
\i events/player_stats_event.sql
\i events/unit_born_event.sql
\i events/unit_died_event.sql
\i events/unit_done_event.sql
\i events/unit_init_event.sql
\i events/upgrade_complete_event.sql
